export const mockData = [
    {
        year: '2021',
        company_id: 'C0609',
        business_unit: 'Chongqing Shuangqiao Chia Tai Co., Ltd.',
        country: 'China',
        gender: 'Male',
        employee: '36308',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '8765',
        temp_emp: '27543',
        employee_under_30: '10374',
        employee_30_50: '20723',
        employee_over_50: '5211',
        employee_c_level: '61',
        employee_evp_level: '111',
        employee_svp_level: '84',
        employee_vp_level: '154',
        employee_avp_level: '252',
        employee_gm_level: '1150',
        employee_dm_level: '2838',
        employee_sm_level: '5420',
        employee_staff_level: '15697',
        employee_worker_level: '10541'
    },
    {
        year: '2021',
        company_id: 'C0107',
        business_unit: 'Shijiazhuang Chia Tai Co., Ltd.',
        country: 'China',
        gender: 'Female',
        employee: '16609',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '3392',
        temp_emp: '13217',
        employee_under_30: '4027',
        employee_30_50: '11263',
        employee_over_50: '1319',
        employee_c_level: '1',
        employee_evp_level: '21',
        employee_svp_level: '15',
        employee_vp_level: '35',
        employee_avp_level: '43',
        employee_gm_level: '270',
        employee_dm_level: '833',
        employee_sm_level: '1916',
        employee_staff_level: '6774',
        employee_worker_level: '6701'
    },
    {
        year: '2021',
        company_id: 'C0507',
        business_unit: 'Huai Hua Chia Tai Co., Ltd.',
        country: 'China',
        gender: 'Male',
        employee: '217',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '204',
        temp_emp: '13',
        employee_under_30: '62',
        employee_30_50: '136',
        employee_over_50: '19',
        employee_c_level: '2',
        employee_evp_level: '0',
        employee_svp_level: '6',
        employee_vp_level: '2',
        employee_avp_level: '22',
        employee_gm_level: '17',
        employee_dm_level: '20',
        employee_sm_level: '65',
        employee_staff_level: '83',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C0807',
        business_unit: 'Ganzhou Chia Tai Industrial Co., Ltd.',
        country: 'China',
        gender: 'Female',
        employee: '166',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '164',
        temp_emp: '2',
        employee_under_30: '79',
        employee_30_50: '81',
        employee_over_50: '6',
        employee_c_level: '1',
        employee_evp_level: '0',
        employee_svp_level: '2',
        employee_vp_level: '0',
        employee_avp_level: '4',
        employee_gm_level: '9',
        employee_dm_level: '21',
        employee_sm_level: '37',
        employee_staff_level: '92',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C1505',
        business_unit: 'Chia Tai Feed (Sui zhou) Co., Ltd.',
        country: 'China',
        gender: 'Male',
        employee: '1062',
        contractor: '18',
        franchisee: '0',
        permanent_emp: '1062',
        temp_emp: '18',
        employee_under_30: '678',
        employee_30_50: '351',
        employee_over_50: '33',
        employee_c_level: '3',
        employee_evp_level: '5',
        employee_svp_level: '24',
        employee_vp_level: '39',
        employee_avp_level: '43',
        employee_gm_level: '91',
        employee_dm_level: '174',
        employee_sm_level: '358',
        employee_staff_level: '265',
        employee_worker_level: '60'
    },
    {
        year: '2021',
        company_id: 'C0661',
        business_unit: 'WUXUAN CHIA TAI ANIMAL HUSBANDRY CO., LTD.',
        country: 'China',
        gender: 'Female',
        employee: '1002',
        contractor: '11',
        franchisee: '0',
        permanent_emp: '1002',
        temp_emp: '11',
        employee_under_30: '646',
        employee_30_50: '320',
        employee_over_50: '36',
        employee_c_level: '1',
        employee_evp_level: '1',
        employee_svp_level: '14',
        employee_vp_level: '18',
        employee_avp_level: '48',
        employee_gm_level: '58',
        employee_dm_level: '143',
        employee_sm_level: '323',
        employee_staff_level: '282',
        employee_worker_level: '114'
    },
    {
        year: '2021',
        company_id: 'C0268',
        business_unit: 'Chia Tai Feed (Yushu) Co., Ltd.',
        country: 'China',
        gender: 'Male',
        employee: '85',
        contractor: '1',
        franchisee: '0',
        permanent_emp: '85',
        temp_emp: '1',
        employee_under_30: '34',
        employee_30_50: '51',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '1',
        employee_vp_level: '1',
        employee_avp_level: '4',
        employee_gm_level: '1',
        employee_dm_level: '5',
        employee_sm_level: '44',
        employee_staff_level: '29',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C0846',
        business_unit: 'Chia Tai Feed (Zhanjiang) Co., Ltd.',
        country: 'China',
        gender: 'Female',
        employee: '38',
        contractor: '4',
        franchisee: '0',
        permanent_emp: '38',
        temp_emp: '4',
        employee_under_30: '15',
        employee_30_50: '23',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '0',
        employee_gm_level: '1',
        employee_dm_level: '5',
        employee_sm_level: '14',
        employee_staff_level: '18',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C0318',
        business_unit: 'Weinan Chia Tai Co.,Ltd.',
        country: 'China',
        gender: 'Male',
        employee: '150',
        contractor: '2',
        franchisee: '0',
        permanent_emp: '150',
        temp_emp: '2',
        employee_under_30: '63',
        employee_30_50: '89',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '2',
        employee_gm_level: '3',
        employee_dm_level: '16',
        employee_sm_level: '64',
        employee_staff_level: '56',
        employee_worker_level: '11'
    },
    {
        year: '2021',
        company_id: 'C0306',
        business_unit: 'Yinchuan Chia Tai Co., Ltd.',
        country: 'China',
        gender: 'Female',
        employee: '61',
        contractor: '1',
        franchisee: '0',
        permanent_emp: '61',
        temp_emp: '1',
        employee_under_30: '32',
        employee_30_50: '30',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '1',
        employee_vp_level: '0',
        employee_avp_level: '2',
        employee_gm_level: '2',
        employee_dm_level: '13',
        employee_sm_level: '22',
        employee_staff_level: '20',
        employee_worker_level: '2'
    },
    {
        year: '2021',
        company_id: 'C0407',
        business_unit: 'Lianyungang Chia Tai Agro-Industry Development Co., Ltd.',
        country: 'China',
        gender: 'Male',
        employee: '143',
        contractor: '4',
        franchisee: '0',
        permanent_emp: '143',
        temp_emp: '4',
        employee_under_30: '85',
        employee_30_50: '62',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '3',
        employee_avp_level: '3',
        employee_gm_level: '5',
        employee_dm_level: '19',
        employee_sm_level: '18',
        employee_staff_level: '88',
        employee_worker_level: '11'
    },
    {
        year: '2021',
        company_id: 'C0129',
        business_unit: 'Hebei C.P. Livestock Co., Ltd.',
        country: 'China',
        gender: 'Female',
        employee: '95',
        contractor: '4',
        franchisee: '0',
        permanent_emp: '95',
        temp_emp: '4',
        employee_under_30: '73',
        employee_30_50: '26',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '1',
        employee_vp_level: '3',
        employee_avp_level: '1',
        employee_gm_level: '4',
        employee_dm_level: '6',
        employee_sm_level: '13',
        employee_staff_level: '33',
        employee_worker_level: '38'
    },
    {
        year: '2021',
        company_id: 'C0612',
        business_unit: 'Mianyang Chia Tai Co., Ltd',
        country: 'China',
        gender: 'Male',
        employee: '52',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '52',
        temp_emp: '0',
        employee_under_30: '17',
        employee_30_50: '33',
        employee_over_50: '2',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '6',
        employee_avp_level: '2',
        employee_gm_level: '5',
        employee_dm_level: '6',
        employee_sm_level: '19',
        employee_staff_level: '14',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C0553',
        business_unit: 'Yichang Chia Tai Animal Husbandry Co., Ltd.（Xiaogan branch）',
        country: 'China',
        gender: 'Female',
        employee: '50',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '50',
        temp_emp: '0',
        employee_under_30: '21',
        employee_30_50: '28',
        employee_over_50: '1',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '1',
        employee_avp_level: '1',
        employee_gm_level: '11',
        employee_dm_level: '4',
        employee_sm_level: '19',
        employee_staff_level: '14',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C0288',
        business_unit: 'Ji Lin De Da Feed Co. Ltd.',
        country: 'China',
        gender: 'Male',
        employee: '1',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '1',
        temp_emp: '0',
        employee_under_30: '0',
        employee_30_50: '1',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '1',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '1',
        employee_gm_level: '0',
        employee_dm_level: '0',
        employee_sm_level: '0',
        employee_staff_level: '0',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C0305',
        business_unit: 'Inner Mongolia Chia Tai Co., Ltd.',
        country: 'China',
        gender: 'Female',
        employee: '0',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '0',
        temp_emp: '0',
        employee_under_30: '0',
        employee_30_50: '0',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '0',
        employee_gm_level: '0',
        employee_dm_level: '0',
        employee_sm_level: '0',
        employee_staff_level: '0',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C0838',
        business_unit: 'Guangdong Chia Tai Ecological Agriculture Co., Ltd.',
        country: 'China',
        gender: 'Male',
        employee: '16',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '16',
        temp_emp: '0',
        employee_under_30: '2',
        employee_30_50: '14',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '1',
        employee_vp_level: '0',
        employee_avp_level: '1',
        employee_gm_level: '6',
        employee_dm_level: '5',
        employee_sm_level: '3',
        employee_staff_level: '0',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: 'C0412',
        business_unit: 'Jiangsu Huai yin Chia Tai Co., Ltd.',
        country: 'China',
        gender: 'Female',
        employee: '9',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '9',
        temp_emp: '0',
        employee_under_30: '1',
        employee_30_50: '8',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '4',
        employee_gm_level: '0',
        employee_dm_level: '2',
        employee_sm_level: '3',
        employee_staff_level: '0',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Thailand',
        gender: 'Male',
        employee: '1062',
        contractor: '18',
        franchisee: '0',
        permanent_emp: '1062',
        temp_emp: '18',
        employee_under_30: '678',
        employee_30_50: '351',
        employee_over_50: '33',
        employee_c_level: '3',
        employee_evp_level: '5',
        employee_svp_level: '24',
        employee_vp_level: '39',
        employee_avp_level: '43',
        employee_gm_level: '91',
        employee_dm_level: '174',
        employee_sm_level: '358',
        employee_staff_level: '265',
        employee_worker_level: '60'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Thailand',
        gender: 'Female',
        employee: '1002',
        contractor: '11',
        franchisee: '0',
        permanent_emp: '1002',
        temp_emp: '11',
        employee_under_30: '646',
        employee_30_50: '320',
        employee_over_50: '36',
        employee_c_level: '1',
        employee_evp_level: '1',
        employee_svp_level: '14',
        employee_vp_level: '18',
        employee_avp_level: '48',
        employee_gm_level: '58',
        employee_dm_level: '143',
        employee_sm_level: '323',
        employee_staff_level: '282',
        employee_worker_level: '114'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Vietnam',
        gender: 'Male',
        employee: '85',
        contractor: '1',
        franchisee: '0',
        permanent_emp: '85',
        temp_emp: '1',
        employee_under_30: '34',
        employee_30_50: '51',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '1',
        employee_vp_level: '1',
        employee_avp_level: '4',
        employee_gm_level: '1',
        employee_dm_level: '5',
        employee_sm_level: '44',
        employee_staff_level: '29',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Vietnam',
        gender: 'Female',
        employee: '38',
        contractor: '4',
        franchisee: '0',
        permanent_emp: '38',
        temp_emp: '4',
        employee_under_30: '15',
        employee_30_50: '23',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '0',
        employee_gm_level: '1',
        employee_dm_level: '5',
        employee_sm_level: '14',
        employee_staff_level: '18',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Myanmar',
        gender: 'Male',
        employee: '150',
        contractor: '2',
        franchisee: '0',
        permanent_emp: '150',
        temp_emp: '2',
        employee_under_30: '63',
        employee_30_50: '89',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '2',
        employee_gm_level: '3',
        employee_dm_level: '16',
        employee_sm_level: '64',
        employee_staff_level: '56',
        employee_worker_level: '11'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Myanmar',
        gender: 'Female',
        employee: '61',
        contractor: '1',
        franchisee: '0',
        permanent_emp: '61',
        temp_emp: '1',
        employee_under_30: '32',
        employee_30_50: '30',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '1',
        employee_vp_level: '0',
        employee_avp_level: '2',
        employee_gm_level: '2',
        employee_dm_level: '13',
        employee_sm_level: '22',
        employee_staff_level: '20',
        employee_worker_level: '2'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Cambodia',
        gender: 'Male',
        employee: '143',
        contractor: '4',
        franchisee: '0',
        permanent_emp: '143',
        temp_emp: '4',
        employee_under_30: '85',
        employee_30_50: '62',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '3',
        employee_avp_level: '3',
        employee_gm_level: '5',
        employee_dm_level: '19',
        employee_sm_level: '18',
        employee_staff_level: '88',
        employee_worker_level: '11'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Cambodia',
        gender: 'Female',
        employee: '95',
        contractor: '4',
        franchisee: '0',
        permanent_emp: '95',
        temp_emp: '4',
        employee_under_30: '73',
        employee_30_50: '26',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '1',
        employee_vp_level: '3',
        employee_avp_level: '1',
        employee_gm_level: '4',
        employee_dm_level: '6',
        employee_sm_level: '13',
        employee_staff_level: '33',
        employee_worker_level: '38'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Philippines',
        gender: 'Male',
        employee: '52',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '52',
        temp_emp: '0',
        employee_under_30: '17',
        employee_30_50: '33',
        employee_over_50: '2',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '6',
        employee_avp_level: '2',
        employee_gm_level: '5',
        employee_dm_level: '6',
        employee_sm_level: '19',
        employee_staff_level: '14',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Philippines',
        gender: 'Female',
        employee: '50',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '50',
        temp_emp: '0',
        employee_under_30: '21',
        employee_30_50: '28',
        employee_over_50: '1',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '1',
        employee_avp_level: '1',
        employee_gm_level: '11',
        employee_dm_level: '4',
        employee_sm_level: '19',
        employee_staff_level: '14',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Malaysia',
        gender: 'Male',
        employee: '1',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '1',
        temp_emp: '0',
        employee_under_30: '1',
        employee_30_50: '28',
        employee_over_50: '1',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '1',
        employee_gm_level: '0',
        employee_dm_level: '0',
        employee_sm_level: '0',
        employee_staff_level: '0',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Malaysia',
        gender: 'Female',
        employee: '0',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '0',
        temp_emp: '0',
        employee_under_30: '0',
        employee_30_50: '0',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '0',
        employee_gm_level: '0',
        employee_dm_level: '0',
        employee_sm_level: '0',
        employee_staff_level: '0',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Indonesia',
        gender: 'Male',
        employee: '16',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '16',
        temp_emp: '0',
        employee_under_30: '2',
        employee_30_50: '14',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '1',
        employee_vp_level: '0',
        employee_avp_level: '1',
        employee_gm_level: '6',
        employee_dm_level: '5',
        employee_sm_level: '3',
        employee_staff_level: '0',
        employee_worker_level: '0'
    },
    {
        year: '2021',
        company_id: '1111',
        business_unit: 'ASCEND',
        country: 'Indonesia',
        gender: 'Female',
        employee: '9',
        contractor: '0',
        franchisee: '0',
        permanent_emp: '9',
        temp_emp: '0',
        employee_under_30: '1',
        employee_30_50: '8',
        employee_over_50: '0',
        employee_c_level: '0',
        employee_evp_level: '0',
        employee_svp_level: '0',
        employee_vp_level: '0',
        employee_avp_level: '4',
        employee_gm_level: '0',
        employee_dm_level: '2',
        employee_sm_level: '3',
        employee_staff_level: '0',
        employee_worker_level: '0'
    },
]